[package]
name = "rdarust-cli"
description = "Command-line interface for rdarust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rdarust"
path = "src/main.rs"

[dependencies]
rdarust-core.workspace = true
rdarust-geo.workspace = true
rdarust-io.workspace = true
clap = { version = "4", features = ["derive"] }
rayon = "1"
serde_json = { version = "1", features = ["float_roundtrip", "preserve_order"] }
anyhow = "1"
serde = "1"
